#!/usr/bin/env bash
# Sherlock launcher: starts the local server (or reuses one already running)
# and triggers a background self-update from the `release` branch for the next launch.

set -uo pipefail

APP_DIR="$HOME/Library/Application Support/Sherlock"
PORT_FILE="$APP_DIR/port.txt"
START_LOCK="$APP_DIR/.starting"
LAUNCH_LOG="$APP_DIR/launcher.log"

mkdir -p "$APP_DIR"
exec >>"$LAUNCH_LOG" 2>&1
echo "[$(date)] launcher invoked"

if [ ! -d "$APP_DIR/.git" ]; then
  echo "ERROR: $APP_DIR is not a git checkout. Run the installer first."
  exit 1
fi

cd "$APP_DIR"

# GUI-launched apps inherit a minimal PATH that almost never includes node/npm
# (nvm and fnm install under $HOME, brew lives at /opt/homebrew or /usr/local).
# install.sh captures the user's interactive shell PATH into .runtime-env;
# we source it. If the file is missing (e.g. an older install that predates
# install.sh capturing PATH), self-heal by capturing it now via `zsh -ic`,
# which spawns an interactive shell that sources ~/.zshrc.
if [ ! -f "$APP_DIR/.runtime-env" ]; then
  CAPTURED_PATH="$(
    zsh  -ic 'printf "%s" "$PATH"' 2>/dev/null \
    || bash -ic 'printf "%s" "$PATH"' 2>/dev/null \
    || echo ""
  )"
  if [ -n "$CAPTURED_PATH" ]; then
    cat > "$APP_DIR/.runtime-env" <<EOF
# Auto-generated by launcher.sh (self-heal). Re-run install.sh to refresh.
export PATH="$CAPTURED_PATH"
EOF
    echo "self-heal: captured shell PATH into .runtime-env"
  fi
fi
if [ -f "$APP_DIR/.runtime-env" ]; then
  # shellcheck source=/dev/null
  source "$APP_DIR/.runtime-env"
else
  export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
fi

check_existing() {
  if [ -f "$PORT_FILE" ]; then
    local port
    port="$(cat "$PORT_FILE" 2>/dev/null || echo "")"
    if [ -n "$port" ] && curl -sf "http://127.0.0.1:$port/api/health" >/dev/null 2>&1; then
      echo "server already running on $port; opening browser"
      open "http://127.0.0.1:$port"
      return 0
    fi
  fi
  return 1
}

# Fast path: existing server
if check_existing; then exit 0; fi

# Stale startup-lock cleanup (>60s old)
if [ -d "$START_LOCK" ]; then
  age=$(( $(date +%s) - $(stat -f %m "$START_LOCK" 2>/dev/null || echo 0) ))
  if [ "$age" -gt 60 ]; then
    echo "removing stale startup lock (age=${age}s)"
    rmdir "$START_LOCK" 2>/dev/null || true
  fi
fi

# Claim the startup lock; if we can't, another launcher is already starting.
if ! mkdir "$START_LOCK" 2>/dev/null; then
  echo "another launcher is starting; waiting"
  for _ in $(seq 1 60); do
    sleep 0.5
    if check_existing; then exit 0; fi
  done
  echo "ERROR: timed out waiting for the other launcher"
  exit 1
fi
trap 'rmdir "$START_LOCK" 2>/dev/null || true' EXIT

# Ensure dist/ is fresh before serving it. The background-update path
# rebuilds when commits arrive, but stale dist/ can still happen after a
# migration (old installer pulled code without building) or if dist/ was
# manually deleted. This check is cheap when dist/ is current (~50ms find).
if [ ! -f "$APP_DIR/dist/index.html" ] \
   || [ -n "$(find "$APP_DIR/web" "$APP_DIR/types" "$APP_DIR/package.json" -newer "$APP_DIR/dist/index.html" 2>/dev/null | head -1)" ]; then
  echo "dist/ is stale or missing; rebuilding frontend (~1s)"
  ( cd "$APP_DIR" && npm run build --silent 2>&1 ) || echo "WARN: build failed; serving previous dist/"
fi

# Start the server detached — it opens its own browser on boot.
echo "starting server"
rm -f "$PORT_FILE"
nohup npm start >"$APP_DIR/server.log" 2>&1 &
SERVER_PID=$!
disown
echo "server pid=$SERVER_PID"

# Background self-update for the NEXT launch (does not affect this one).
(
  echo "[$(date)] update: starting"
  old_head="$(git rev-parse HEAD 2>/dev/null || echo none)"
  if ! git fetch origin release 2>/dev/null; then
    echo "[$(date)] update: fetch failed (offline or no release branch yet); skipping"
    exit 0
  fi
  old_lock="$(shasum -a 256 package-lock.json 2>/dev/null | cut -d' ' -f1)"
  old_bundle_hash="$(find "$APP_DIR/packaging/Sherlock.app" -type f 2>/dev/null | sort | xargs shasum -a 256 2>/dev/null | shasum -a 256 | cut -d' ' -f1)"
  if ! git reset --hard origin/release 2>/dev/null; then
    echo "[$(date)] update: reset failed; skipping"
    exit 0
  fi
  new_head="$(git rev-parse HEAD 2>/dev/null || echo none)"
  if [ "$old_head" = "$new_head" ]; then
    echo "[$(date)] update: already up to date ($new_head)"
    exit 0
  fi
  echo "[$(date)] update: $old_head -> $new_head"
  new_lock="$(shasum -a 256 package-lock.json 2>/dev/null | cut -d' ' -f1)"
  new_bundle_hash="$(find "$APP_DIR/packaging/Sherlock.app" -type f 2>/dev/null | sort | xargs shasum -a 256 2>/dev/null | shasum -a 256 | cut -d' ' -f1)"
  if [ "$old_lock" != "$new_lock" ]; then
    echo "[$(date)] update: package-lock changed, running npm install"
    npm install --silent 2>&1 || echo "[$(date)] update: npm install failed"
  fi
  # Rebuild the frontend so new web/ code is actually served on next launch.
  # `dist/` is gitignored, so `git reset` doesn't touch it — we must rebuild.
  echo "[$(date)] update: rebuilding frontend"
  npm run build --silent 2>&1 || echo "[$(date)] update: build failed"
  # Refresh /Applications/Sherlock.app when the bundle (icon, Info.plist, MacOS script) changed.
  if [ "$old_bundle_hash" != "$new_bundle_hash" ] && [ -d "$APP_DIR/packaging/Sherlock.app" ]; then
    echo "[$(date)] update: .app bundle changed, refreshing /Applications/Sherlock.app"
    rm -rf "/Applications/Sherlock.app.tmp"
    if cp -R "$APP_DIR/packaging/Sherlock.app" "/Applications/Sherlock.app.tmp" 2>/dev/null; then
      rm -rf "/Applications/Sherlock.app"
      mv "/Applications/Sherlock.app.tmp" "/Applications/Sherlock.app"
      # Tell LaunchServices to re-read the bundle so the new icon shows up.
      /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
        -f "/Applications/Sherlock.app" 2>/dev/null || true
      echo "[$(date)] update: .app bundle refreshed"
    else
      echo "[$(date)] update: .app bundle refresh failed (no write access?); leaving previous version"
    fi
  fi
  echo "[$(date)] update: complete (applies on next launch)"
) >>"$APP_DIR/update.log" 2>&1 &
disown

# Release the lock once port.txt is written (server is responsive).
for _ in $(seq 1 60); do
  if [ -f "$PORT_FILE" ]; then
    echo "server booted; launcher exiting"
    exit 0
  fi
  sleep 0.5
done
echo "WARN: server did not write port.txt within 30s"
exit 0
