#!/usr/bin/env bash
# Sherlock launcher: starts the local server (or reuses one already running)
# and triggers a background self-update from the `release` branch for the next launch.

set -uo pipefail

APP_DIR="$HOME/Library/Application Support/Sherlock"
PORT_FILE="$APP_DIR/port.txt"
START_LOCK="$APP_DIR/.starting"
LAUNCH_LOG="$APP_DIR/launcher.log"

mkdir -p "$APP_DIR"
exec >>"$LAUNCH_LOG" 2>&1
echo "[$(date)] launcher invoked"

if [ ! -d "$APP_DIR/.git" ]; then
  echo "ERROR: $APP_DIR is not a git checkout. Run the installer first."
  exit 1
fi

cd "$APP_DIR"

# GUI-launched apps inherit a minimal PATH that almost never includes node/npm
# (nvm and fnm install under $HOME, brew lives at /opt/homebrew or /usr/local).
# install.sh captures the user's interactive shell PATH into .runtime-env;
# we source it. If the file is missing (e.g. an older install that predates
# install.sh capturing PATH), self-heal by capturing it now via `zsh -ic`,
# which spawns an interactive shell that sources ~/.zshrc.
if [ ! -f "$APP_DIR/.runtime-env" ]; then
  CAPTURED_PATH="$(
    zsh  -ic 'printf "%s" "$PATH"' 2>/dev/null \
    || bash -ic 'printf "%s" "$PATH"' 2>/dev/null \
    || echo ""
  )"
  if [ -n "$CAPTURED_PATH" ]; then
    cat > "$APP_DIR/.runtime-env" <<EOF
# Auto-generated by launcher.sh (self-heal). Re-run install.sh to refresh.
export PATH="$CAPTURED_PATH"
EOF
    echo "self-heal: captured shell PATH into .runtime-env"
  fi
fi
if [ -f "$APP_DIR/.runtime-env" ]; then
  # shellcheck source=/dev/null
  source "$APP_DIR/.runtime-env"
else
  export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
fi

check_existing() {
  if [ -f "$PORT_FILE" ]; then
    local port
    port="$(cat "$PORT_FILE" 2>/dev/null || echo "")"
    if [ -n "$port" ] && curl -sf "http://127.0.0.1:$port/api/health" >/dev/null 2>&1; then
      echo "server already running on $port; opening browser"
      open "http://127.0.0.1:$port"
      return 0
    fi
  fi
  return 1
}

# Fire a background self-update. Used by both the fast-path (warm click on
# an already-running server) and the cold-start path. Uses an update-lock
# so multiple clicks in quick succession don't run concurrent npm installs.
run_background_update() {
  local update_lock="$APP_DIR/.updating"
  if [ -d "$update_lock" ]; then
    local age
    age=$(( $(date +%s) - $(stat -f %m "$update_lock" 2>/dev/null || echo 0) ))
    if [ "$age" -lt 600 ]; then
      echo "another update already running (age=${age}s); skipping"
      return 0
    fi
    rmdir "$update_lock" 2>/dev/null || true
  fi
  if ! mkdir "$update_lock" 2>/dev/null; then
    return 0
  fi
  (
    trap 'rmdir "$update_lock" 2>/dev/null || true' EXIT
    echo "[$(date)] update: starting"
    old_head="$(git rev-parse HEAD 2>/dev/null || echo none)"
    # Stale .git/index.lock can be left behind if a previous git operation
    # was killed (interrupted launcher, system sleep mid-fetch). Clean it up
    # if it's older than 60 seconds so we don't get stuck forever.
    if [ -f "$APP_DIR/.git/index.lock" ]; then
      lock_age=$(( $(date +%s) - $(stat -f %m "$APP_DIR/.git/index.lock" 2>/dev/null || echo 0) ))
      if [ "$lock_age" -gt 60 ]; then
        echo "[$(date)] update: removing stale .git/index.lock (age=${lock_age}s)"
        rm -f "$APP_DIR/.git/index.lock"
      fi
    fi
    if ! fetch_err="$(git fetch origin release 2>&1)"; then
      echo "[$(date)] update: fetch failed; skipping"
      echo "[$(date)] update:   $fetch_err"
      exit 0
    fi
    old_lock="$(shasum -a 256 package-lock.json 2>/dev/null | cut -d' ' -f1)"
    old_bundle_hash="$(find "$APP_DIR/packaging/Sherlock.app" -type f 2>/dev/null | sort | xargs shasum -a 256 2>/dev/null | shasum -a 256 | cut -d' ' -f1)"
    if ! reset_err="$(git reset --hard origin/release 2>&1)"; then
      echo "[$(date)] update: reset failed; skipping"
      echo "[$(date)] update:   $reset_err"
      # Try to recover from common failure modes
      if echo "$reset_err" | grep -qi "index.lock"; then
        echo "[$(date)] update: detected lock file in error; removing and retrying"
        rm -f "$APP_DIR/.git/index.lock"
        if ! reset_err2="$(git reset --hard origin/release 2>&1)"; then
          echo "[$(date)] update: retry also failed: $reset_err2"
          exit 0
        fi
      elif echo "$reset_err" | grep -qi "local changes"; then
        echo "[$(date)] update: detected dirty working tree; stashing and retrying"
        git stash push -u -m "auto-stash-pre-update-$(date +%s)" 2>&1 || true
        if ! reset_err2="$(git reset --hard origin/release 2>&1)"; then
          echo "[$(date)] update: retry also failed: $reset_err2"
          exit 0
        fi
      else
        exit 0
      fi
    fi
    new_head="$(git rev-parse HEAD 2>/dev/null || echo none)"
    if [ "$old_head" = "$new_head" ]; then
      echo "[$(date)] update: already up to date ($new_head)"
      exit 0
    fi
    echo "[$(date)] update: $old_head -> $new_head"
    printf '{"state":"updating","at":%s}\n' "$(date +%s)" > "$APP_DIR/.update-status"
    new_lock="$(shasum -a 256 package-lock.json 2>/dev/null | cut -d' ' -f1)"
    new_bundle_hash="$(find "$APP_DIR/packaging/Sherlock.app" -type f 2>/dev/null | sort | xargs shasum -a 256 2>/dev/null | shasum -a 256 | cut -d' ' -f1)"
    if [ "$old_lock" != "$new_lock" ]; then
      echo "[$(date)] update: package-lock changed, running npm install"
      npm install --silent 2>&1 || echo "[$(date)] update: npm install failed"
    fi
    # Rebuild the frontend. `dist/` is gitignored so git reset doesn't touch it.
    # Importantly: Fastify serves `dist/` from disk on each request, so a browser
    # refresh will pick up the new frontend without needing a server restart.
    echo "[$(date)] update: rebuilding frontend"
    npm run build --silent 2>&1 || echo "[$(date)] update: build failed"
    if [ "$old_bundle_hash" != "$new_bundle_hash" ] && [ -d "$APP_DIR/packaging/Sherlock.app" ]; then
      echo "[$(date)] update: .app bundle changed, refreshing /Applications/Sherlock.app"
      rm -rf "/Applications/Sherlock.app.tmp"
      if cp -R "$APP_DIR/packaging/Sherlock.app" "/Applications/Sherlock.app.tmp" 2>/dev/null; then
        rm -rf "/Applications/Sherlock.app"
        mv "/Applications/Sherlock.app.tmp" "/Applications/Sherlock.app"
        /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
          -f "/Applications/Sherlock.app" 2>/dev/null || true
        echo "[$(date)] update: .app bundle refreshed"
      else
        echo "[$(date)] update: .app bundle refresh failed (no write access?); leaving previous version"
      fi
    fi
    printf '{"state":"updated","at":%s,"head":"%s"}\n' "$(date +%s)" "$new_head" > "$APP_DIR/.update-status"
    echo "[$(date)] update: complete (frontend live on next browser refresh; server-side code on next cold start)"
  ) >>"$APP_DIR/update.log" 2>&1 &
  disown
}

# Fast path: existing server is alive. Open a tab and also fire a background
# update — that way warm clicks still pull new frontend code without forcing
# the user to quit and relaunch.
if check_existing; then
  run_background_update
  exit 0
fi

# Stale startup-lock cleanup (>60s old)
if [ -d "$START_LOCK" ]; then
  age=$(( $(date +%s) - $(stat -f %m "$START_LOCK" 2>/dev/null || echo 0) ))
  if [ "$age" -gt 60 ]; then
    echo "removing stale startup lock (age=${age}s)"
    rmdir "$START_LOCK" 2>/dev/null || true
  fi
fi

# Claim the startup lock; if we can't, another launcher is already starting.
if ! mkdir "$START_LOCK" 2>/dev/null; then
  echo "another launcher is starting; waiting"
  for _ in $(seq 1 60); do
    sleep 0.5
    if check_existing; then exit 0; fi
  done
  echo "ERROR: timed out waiting for the other launcher"
  exit 1
fi
trap 'rmdir "$START_LOCK" 2>/dev/null || true' EXIT

# Ensure dist/ is fresh before serving it. The background-update path
# rebuilds when commits arrive, but stale dist/ can still happen after a
# migration (old installer pulled code without building) or if dist/ was
# manually deleted. This check is cheap when dist/ is current (~50ms find).
if [ ! -f "$APP_DIR/dist/index.html" ] \
   || [ -n "$(find "$APP_DIR/web" "$APP_DIR/types" "$APP_DIR/package.json" -newer "$APP_DIR/dist/index.html" 2>/dev/null | head -1)" ]; then
  echo "dist/ is stale or missing; rebuilding frontend (~1s)"
  ( cd "$APP_DIR" && npm run build --silent 2>&1 ) || echo "WARN: build failed; serving previous dist/"
fi

# Start the server detached — it opens its own browser on boot.
# Pass SHERLOCK_BOOT_SHA so the server knows what commit it's running, which
# /api/version compares against the on-disk HEAD to detect pending updates.
echo "starting server"
rm -f "$PORT_FILE"
BOOT_SHA="$(git rev-parse HEAD 2>/dev/null || echo unknown)"
SHERLOCK_BOOT_SHA="$BOOT_SHA" nohup npm start >"$APP_DIR/server.log" 2>&1 &
SERVER_PID=$!
disown
echo "server pid=$SERVER_PID (boot sha=$BOOT_SHA)"

# Background self-update — also runs on warm clicks via the fast-path above.
run_background_update

# Release the lock once port.txt is written (server is responsive).
for _ in $(seq 1 60); do
  if [ -f "$PORT_FILE" ]; then
    echo "server booted; launcher exiting"
    exit 0
  fi
  sleep 0.5
done
echo "WARN: server did not write port.txt within 30s"
exit 0
